Add missing #include<cstddef>
Adding #include <cstddef> suppresses the compilation error `error: unknown type name 'size_t'` issued by Clang 17 on macOS.